### ISSUE TITLE
Delete branch after merging

### ISSUE THREAD

**Issue by SanketDG** [adtac/cherry-pick-bot#4]

**Comment by adtac** [comment]
It uses one branch per repo (it pushes to the same branch all the time), but this would be nice yes.

**Comment by SanketDG** [comment]
Oh! Then it is unncessary, what do you think?

I just saw the delete branch button after merge, and my github OCD kicked in.

**Comment by adtac** [comment]
I dunno, one branch doesn't exactly clutter the branch list so it shouldn't really be a problem. But on the other hand it's not really an issue. Even if the branch is deleted, the next push will create another one easily.
