### ISSUE TITLE
Use actual config files

### ISSUE THREAD

**Issue by yukiisbored** [adtac/cherry-pick-bot#6]
It's better to have an actual editable at runtime files rather than a config file that'll be included in the resulting binary.

**Comment by adtac** [comment]
How about environment variables? `PRIVATE_KEY`, `GITHUB_EMAIL`, `GITHUB_ACCESS_TOKEN`?

**Comment by yukiisbored** [comment]
It's not persistent as config files, it should be used when the config file doesn't exist.
